#!/bin/csh -f
# Copyright (C) 2003 Tensilica, Inc.  All Rights Reserved.
# Revised to support Tensilica processors and to improve overall performance
### ====================================================================
### ====================================================================
###
### Module: gen_gtn_set
### $Revision: 1.3 $
### $Date: 1997/08/22 02:26:22 $
### $Author: ho $
### $Source: /isms/cmplrs.src/osprey1.0/be/cg/RCS/gen_gtn_set,v $
### Revision history:
###   5-May-92 - Original version
###
### Usage:      gen_gtn_set utildir opts
###
###     Generate the gtn_set.[ch] module.  'Utildir' is where to find
###     the gen_x_set stuff. 'Opts' is passed as the first argument
###     to gen_x_set to allow specification of functional or macro
###     interfaces.
###
###     We do this in a file so the make rule can depend on it and
###     the modules can be rebuilt when the procedure changes
###
### ====================================================================
### ====================================================================


${STDTOOLS}/bin/perl $1/gen_x_set $2                                    \
                gtn_set                                                 \
                'TN*'                                                   \
                GTN_SET                                                 \
                GTN_UNIVERSE_TN_int                                     \
                GTN_UNIVERSE_INT_tn                                     \
                'defs.h'                                                \
                'tn.h'                                                  \
                'gtn_universe.h'                                        \
                'mempool.h'



