
/* 
   Copyright (C) 2001 Tensilica, Inc.  All Rights Reserved.
   Revised to support Tensilica processors and to improve overall performance
 */

/*WARNING: This file is automatically generated!*/
int prepends_underscore = 0;
